#!/bin/bash
set -e

source /opt/app-root/etc/generate_container_user


echo -e "Running as user $(id)"

echo "Running this container is only recommended when running in test or development."
echo "It is recommended to use this s2i image as a pure builder image and use it with an openshift chain build https://docs.okd.io/latest/dev_guide/builds/advanced_build_operations.html#dev-guide-chaining-builds"

if [ ! -z "$MKDOCS_RUN" ]; then
  echo "---> Running application ($MKDOCS_RUN) ..."
  $MKDOCS_RUN
else
  echo "---> Running application (mkdocs serve --no-livereload  --dev-addr 0.0.0.0:$DEPLOY_PORT) ..."
  mkdocs serve --no-livereload  --dev-addr 0.0.0.0:$DEPLOY_PORT
fi