#!/bin/sh

cat <<EOF
This is a S2I base image for Web Applications:
To use it, install S2I: https://github.com/openshift/source-to-image

Sample invocation:
s2i build https://github.com/openshift-examples/web.git quay.io/openshift-examples/ubi8-s2i-mkdocs:latest openshift-example

You can then run the resulting image via:
docker run -p 8080:8080 openshift-example
EOF
